### ISSUE TITLE
Did you find a solution to make it work?

### ISSUE THREAD

**Issue by connor11528** [SebastianS90/laravel-mix-vue-router#1]
Solution for using Laravel and Vue Router

**Comment by SebastianS90** [comment]
I don't use laravel-mix anymore (I have my own webpack configuration instead), so I don't know about the current status of this problem.

The issue i opened was JeffreyWay/laravel-mix#164 and I fixed it with JeffreyWay/laravel-mix#209.
But according to [a comment](https://github.com/JeffreyWay/laravel-mix/issues/164#issuecomment-315596718), the fix was removed in a later version.
There is a new issue for that problem with a suggested solution in the comments: JeffreyWay/laravel-mix#209

**Comment by connor11528** [comment]
Okay got it thank you
